[package]
name = "mini-submit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "=0.5.0-rc.3"
handlebars = "4.4.0"
base64 = "0.21.4"
